### ISSUE TITLE
FeatureRequest: Share results to other chat rooms

### ISSUE THREAD

**Issue by shrimp509** [cofacts/rumors-line-bot#186]
Hi all,

I really enjoy your works with cofacts chatbot.
I can easily distinguish the truth of messages from my parents, that is reeeally good.

However, there is a feature that I need is not in the current version.
The feature I need is `sharing the results to other chat rooms`, such as my parent's private message or family channel etc.

Thanks for your effort. You are the best.

**Comment by MrOrz** [comment]
Hi @shrimp509 it's glad to see the chatbot helps :)

If you feel like sharing the results from Cofacts to other chatrooms, you may either
1. long-press the replies and choose "share". After that you can select multiple messages to share (usually the reason and the references provided by the editor) and then choose the target chatrooms.
2. When the chatbot asks if the reply is useful, reply "yes". The chatbot will then encourage you to share this reply with friends.

Option 2 works like this:
![Screenshot_20200507-004353_2](https://user-images.githubusercontent.com/108608/81205116-d23d8880-8ffc-11ea-9a15-fb2cd86e87b8.png)
![Screenshot_20200507-004411](https://user-images.githubusercontent.com/108608/81205127-d5387900-8ffc-11ea-819c-a0b28bb97ef4.png)

We designed this flow because we really needs the user's feedback on usefulness of the reply, and we don't want to ask user to share a reply if they think it's not useful in the first place.

**Comment by shrimp509** [comment]
Got it!! I didn't notice the share button after choosing one of the results.
Thanks for your detail explanation of why you design like this.
I understand your consideration. Thank you again.
