### ISSUE TITLE
On-boarding tutorial

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#216]
Related discussion: https://g0v.hackmd.io/eitM7s0bSSeS3kg-MAcpDw#LINE-bot-onboarding-UX

## Target
1. Provide basic usage instruction
2. Experience lookup interaction
3. Setup LIFF permissions

## Trigger
- Join event
- Rich menu

### 1. Welcome
> This is a chatbot that looks up suspicious forwarded messages for you. Here is how to use me:
> 我是幫你查轉傳訊息的機器人。用法像這樣 

Flex message carousel:
1. When receiving a message from elsewhere / 在他處收到訊息 
2. Long press and share / 長按後分享
3. Select Cofacts to share / 指名 Cofacts
4. Cofacts replies with a crowd-sourced fact-check or chatbot replies / Cofacts 回傳網撰寫的的查證或回應

> Wanna try it out? Just forward a message to me!
> 是不是躍躍欲試呢？試試把訊息傳進來吧！
>
> [按鈕] Simulates forwarding a message / 模擬傳訊息進 Cofacts
 
### 2. Show mock reply

(Reply content without voting)

> [Quick reply] 💡 Cool, I got it! 酷，我懂了！
> [Quick reply]  🤔 What happened? 發生什麼事？

### 3. Provide setup

"Cool, I got it!" -->
> You are smart 😊  你很聰明 😊

"What happened?" -->
> ⬆️ What you see above is a simulation of what you may see after you forward a message to Cofacts. 上面在模擬你傳訊息給我時，會得到的回應。
> 📚 Cofacts has a database of hoax messages and replies. Cofacts 有一個謠言與回應的資料庫。
> 📲 When you send a message to me, I look up the message in our database and return the results I found. 當你傳訊息給我的時候，我會搜尋資料庫然後回傳找到的結果。
> 🆕 If I can't find anything, I will ask you about sending your message to that database. 如果我找不到的話，會徵求你的同意，看看要不要把這個訊息送進資料庫唷。

> To wrap up, please finish your permission settings so that I can provide a smoother experience.
> [按鈕] Setup permission / 權限設定
> [Quick reply]👌 Done! / 我設好了！
> [Quick reply] ⏱️ Later / 之後再設吧
> [Quick reply] ❓ Why setup permission? / 為什麼要設這個？

### 3.5 Explaination
“❓ Why setup permission?” -->
> When I provide hoax-busting replies to you, I would like to ask you for any feedback on the crowd-sourced reply. 
> In order to achieve that, I need to ask for your permission to "send your message to our chatroom".
> The permission will be used to send only this one message of yours back to this particular chatroom.
> You can still use Cofacts without granting me this permission. When we ask for feedback from you, the permission dialog will pop-up again.

### 4. Thank-you

"⏱️ Later" -->
> OK. When we ask for feedback from you, the permission dialog will pop-up again.

> This is the end of the tutorial. Next time when you receive a suspicious message, don't hesitate to forward it to me! 🤗

**Comment by MrOrz** [comment]
English wording has been revised. Kudos to Jack for revisiting these words!

**Comment by MrOrz** [comment]
「模擬傳訊息」`displayText` https://developers.line.biz/en/reference/messaging-api/#postback-action max 300 characters

> (牛奶加一物，三高、痛風、癌症都不見了！姐夫82歲了還活力無窮！轉發出去功德無量！)
>
> 只要每天早上一杯地瓜葉牛奶。不僅有效降低三高，甚至連痛風也沒了；此外，地瓜葉牛奶的作法也很簡單，只要先將地瓜葉川燙過後，再加入鮮奶打成汁即可。

**Comment by MrOrz** [comment]
Images:
https://www.dropbox.com/sh/y3mt06zvahge4cd/AACwWy77wDd9La0ICViOC56Ea?dl=0

- 1: Greeting
- 2~5: Flex message carousel
- 6: Thank you

**Comment by bil4444** [comment]
To wrap up, please finish your permission settings so that I can provide a smoother experience.
現在請你設定「如果你之後問的問題被查證了要回傳給你」，這需要經過你的同意喔！





Why setup permission?” -->
為什麼要同意呢？這要設定什麼？


When I provide hoax-busting replies to you, I would like to ask you for any feedback on the crowd-sourced reply.
In order to achieve that, I need to ask for your permission to "send your message to our chatroom".
The permission will be used to send only this one message of yours back to this particular chatroom.
You can still use Cofacts without granting me this permission. When we ask for feedback from you, the permission dialog will pop-up again.



當我把查到的闢謠回給你的時候，我會請你一起確認「這個機器人沒有答非所問」，有你的幫助與按讚👍確認，能讓我學習很多、查得更好。
不過我是個很有禮貌的機器人，我會徵求你的同意讓我傳訊息告訴你：「你剛剛問我的訊息，真的假的聊天機器人 查到了，答案是什麼」。
這個設定可以讓我在幫你查到新訊息的時候告訴你「剛剛你傳的訊息是真的還是假的。」
如果你選擇關閉這個設定，你還是可以問機器人那些別人有問過、或我已經幫別人查過的舊訊息。

如果之後 真的假的 機器人需要請求你的幫忙，再來問你喔！
4. Thank-you
好喔我懂了！
"⏱️ Later" -->
之後再設定吧！
OK. When we ask for feedback from you, the permission dialog will pop-up again.
好的，如果之後 真的假的 機器人需要請求你的幫忙，再來問你喔！

This is the end of the tutorial. Next time when you receive a suspicious message, don't hesitate to forward it to me! 🤗
耶咿～教學結束囉！！
下次收到可疑的訊息時，就轉傳分享給我幫你查吧！😊

**Comment by MrOrz** [comment]
> In order to achieve that, I need to ask for your permission to "send your message to our chatroom".
> The permission will be used to send only this one message of yours back to this particular chatroom.

這兩句其實是在講 #174 的「傳送訊息至聊天室」權限。

因為之前就有發生過[使用者問為什麼要這個「傳送訊息至聊天室」權限]( https://www.facebook.com/groups/cofacts/permalink/2672723192959493/)，所以才會有這個說明文字。如果我們不用這個中文字，使用者會不知道我們在解釋什麼。

LINE UI 使用的英文是 "Send messages to chats"，而中文是「傳送訊息至聊天室」，這個部分的說明，英文與中文應該都要跟 LINE 的 UI 一致。

![Screenshot_20201029-134319](https://user-images.githubusercontent.com/108608/97530444-1bd7c080-19ed-11eb-9d12-08147a9e374e.png)
![](https://user-images.githubusercontent.com/44064051/80186988-790b4780-8641-11ea-8aa5-721316638211.jpg)

**Comment by bil4444** [comment]
To wrap up, please finish your permission settings so that I can provide a smoother experience.
現在請你完成設定，讓機器人的事實查核順利進行喔！

Why setup permission?” -->
為什麼要同意呢？這要設定什麼？

When I provide hoax-busting replies to you, I would like to ask you for any feedback on the crowd-sourced reply.
In order to achieve that, I need to ask for your permission to "send your message to our chatroom".
The permission will be used to send only this one message of yours back to this particular chatroom.
You can still use Cofacts without granting me this permission. When we ask for feedback from you, the permission dialog will pop-up again.

當我把查到的闢謠回給你的時候，我會請你一起確認「這個機器人沒有答非所問」，有你的幫助與按讚👍確認，能讓我學習很多、查得更好。
要得到你的「👍 」，或是「這回得不好，機器人應該改成oxxxx」所以需要請你許可『傳送訊息至聊天室』。

如果不同意的話，還是可以使用其他功能喔！如果我們需要你幫忙，這個「請求同意」的對話會再次出現。

**Comment by bil4444** [comment]
This is the end of the tutorial. Next time when you receive a suspicious message, don't hesitate to forward it to me! 🤗
耶咿～教學結束囉！！
下次收到可疑的訊息時，就轉傳分享給我幫你查吧！😊




To wrap up, please finish your permission settings so that I can provide a smoother experience.
現在請你完成設定，讓機器人的事實查核順利進行喔！

Why setup permission?” -->
為什麼要同意呢？這要設定什麼？

When I provide hoax-busting replies to you, I would like to ask you for any feedback on the crowd-sourced reply.
In order to achieve that, I need to ask for your permission to "send your message to our chatroom".
The permission will be used to send only this one message of yours back to this particular chatroom.
You can still use Cofacts without granting me this permission. When we ask for feedback from you, the permission dialog will pop-up again.

當我把查到的闢謠回給你的時候，我會需要跟你對話確認才不會誤會你的意思，所以請幫我選擇許可「傳送訊息至聊天室」 。
一樣只會在 真的假的 的好友帳號裡面，讓你可以查新的謠言。

如果不同意的話，還是可以使用其他功能喔！如果我們需要你幫忙，這個「請求同意」的對話會再次出現。
