### ISSUE TITLE
Ask user the reason why they think a reply is not helpful

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#70]
When the user responded "No" when we ask "Do you think the reply is helpful", we should ask the user for the reason.

### The reply text for "No" user input:
1. `請問您為什麼覺得好心人的回應沒有幫助？請按左下角「⌨️」鈕，把理由傳給我們，幫助闢謠編輯釐清問題所在；若不想填，請按「我不想填理由」按鈕。`
2. Button: `我不想填理由`

### After the user responded with a reason or pressed "我不想填理由"：
1. First feedback:`感謝您的回饋，您是第一個評論這份文章與回應的人 :)` / Not first feedback: `感謝您與其他 1 人的回饋。`

API: cofacts/rumors-api#75

**Comment by changhc** [comment]
I'm working on this

**Comment by changhc** [comment]
This sounds reasonable, but it also leads to overhead and dissatisfaction if the user submitted their reason immediately.

What about using the response time to determine if we need a confirmation? For example, at time = T the user selected "article not useful". If he submitted another message at T + N and N is greater than some threshold, say, 1 hour, the bot would ask for confirmation. Of course this still leads to vulnerability to attacks from some bored users... so just skip this.

But still, it's good to give users a second chance to review their reviews to be sent. I'll add a state ASKING_NOT_USEFUL_FEEDBACK_CONFIRM. Is this okay?

**Comment by MrOrz** [comment]
I think confirmation step also can help users that submits reasons immediately.
They may hit send button accidentally when typing on phone, so having a consistent confirmation step can provide a safety net for that.

`ASKING_NOT_USEFUL_FEEDBACK_CONFIRM` is a good name. But I would also consider names like `ASKING_NOT_USEFUL_FEEDBACK_SUBMISSION`, which is after article confirmation state's name [`ASKING_REPLY_REQUEST_SUBMISSION `](https://github.com/cofacts/rumors-line-bot/pull/84/files#diff-53badf5a94c9e43c5793b09c5be78115R94).

**Comment by changhc** [comment]
Sure. I'll use that name.

**Comment by changhc** [comment]
Now if a user clicks 「重寫送出的理由」, the bot replies 「好的，請重新填寫理由」. Should I add a 「我不想填理由」button to this reply as well? They can click the previous button, but I'm just wondering if this is more convenient.

**Comment by MrOrz** [comment]
@changhc sounds reasonable. If it does not complicate the code too much, please do. Thanks!

**Comment by changhc** [comment]
PR submitted.

I'm not sure which of these events should also be tracked by GA. Now we're tracking if users consider the reply useful in the state ASKING_REPLY_FEEDBACK and we know if they clicked Y/N, but I'm not sure if we need to track their comments.

Also, maybe in the state ASKING_REPLY_FEEDBACK we should filter the reply with `event.type` rather than determining the next state using *only* `event.input`. If the user types something rather than clicking the button, this may lead to unexpected result. For example, they type "是" directly, but this is not "y" (the postback answer) so our system goes to the "not useful" state. If the event type is text, maybe we should stay in the same state and ask them to click the button. Though this leads to some dissatisfaction, it's much easier than handling all input patterns like "是", "否", "沒用", etc..

**Comment by MrOrz** [comment]
Should be closed by #83 and #85
