### ISSUE TITLE
Some text in the button template is cropped

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#75]
As reported in FB: https://www.facebook.com/groups/cofacts/permalink/2133012516930566/
Maybe we should adjust number of words in the message.

**Comment by nonumpa** [comment]
This bug is caused by #68.
[Text](https://developers.line.me/en/docs/messaging-api/reference/#text-message
) message is max 2000 characters but [template](https://developers.line.me/en/docs/messaging-api/reference/#template-messages) messages are by cases.

In this case we use  `Buttons template` which limitation is :
> Message text
> Max: 160 characters (no image or title)
> Max: 60 characters (message with an image or title)

Maybe we can replace it by  `Confirm template` which limitation is :
> Message text
> Max: 240 characters

And [here](https://developers.line.me/en/docs/messaging-api/message-types/#template-messages) can see how `Confirm template` looks like.

**Comment by MrOrz** [comment]
Hmm I remembered that LINE messaging API would emit 400 if we exceed word limit. Maybe the behavior has changed.

Didn't know that there is confirm template. +1 for switching to it.
Thanks a lot!
